version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}

      - run: ./gradlew downloadDependencies --daemon
      - save_cache:
          key: gradle-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

      - run:
          name: Run Unit Tests
          command: ./gradlew test --daemon
      - run:
          name: Run Integration Tests
          command: ./gradlew integrationTest --daemon
  docs:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run:
          name: Download Script
          command: mkdir $HOME/script && curl -o $HOME/script/create_pr.bash https://https://raw.githubusercontent.com/elasticio/elasticio.github.io/master/scripts/create_pr.bash
      - run:
          shell: /bin/bash
          name: Create PR
          command: bash $HOME/script/create_pr.bash -p $PWD -n utility-component

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
  deploy_docs:
    jobs:
      - docs:
          filters:
            branches:
              only:
                - master
                - docs-automation